name = "Queer Minecraft Server Modpack"
author = "arc2-group"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f2cdd5415d114f0e14f037b05140bd21a7acd6baf480b70d4a93b459ba8e24ae"

[versions]
fabric = "0.18.3"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.21.10"]
