name = "Queer Minecraft Server Modpack"
author = "arc2-group"
version = "2.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "488d1ac526eacbb84ef47819152062d2c33266ebd5060cfefa4af87eb13ae83b"

[versions]
fabric = "0.18.3"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.21.10"]
