name = "Queer Minecraft Server Modpack"
author = "arc2-group"
version = "2.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9a9048a71b5b34f842d3a53ec0dd5a4de29cce4b71a5b6359f625aebad400a7d"

[versions]
fabric = "0.18.3"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.21.10"]
