name = "Queer Minecraft Server Modpack"
author = "arc2-group"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "26158a18475b0eaab1ad141edb8a967003336d7a338a0dfa7c470474c3a0b70f"

[versions]
fabric = "0.18.3"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.21.10"]
