hash-format = "sha256"

[[files]]
file = "codeofconduct/en_us.txt"
hash = "4e96a826c3c3a2cecf04a72fe40cc0dfc7f43df0a7adc6e01c49daef1a974cb0"

[[files]]
file = "config/EasyAuth/extended.conf"
hash = "9e7d0bf997c396baba88dc1ed71eb849e805bbd2dbf226eb1c33660804b5b37d"

[[files]]
file = "config/EasyAuth/main.conf"
hash = "acd28cb942efda88e64d3696fd399df601c008aa9b0341b6cc90568f470acfc1"

[[files]]
file = "config/EasyAuth/storage.conf"
hash = "f48492909742061009b84298893d2c6dde55301ec3447da24bc52d4e9e89a1cf"

[[files]]
file = "config/EasyAuth/technical.conf"
hash = "ad1e69d75a75503779ac12af9ec7462c4fdfe2f8087504b1b08fe9f108338471"

[[files]]
file = "config/EasyAuth/translation.conf"
hash = "4d06ea53d4a6699060e7c15e95b4a9996bd6801bb084034a79a84a76aee42b1f"

[[files]]
file = "config/Geyser-Fabric/config.yml"
hash = "d68e3625b3e62d5dd88faaf26e1e8b1e6737587dc122df68f115d0f7d2f2997e"

[[files]]
file = "config/GrimAC/config.yml"
hash = "ccad5b06a0c01b09ea84e1691423aaae0672e401d29eda43dca468432a7179a8"

[[files]]
file = "config/ViaFabric/viaversion.yml"
hash = "563cdfca497a81cb7739cb2f01cc6ded303a5e22e6edb4ba3cbdb3a07cd5578b"

[[files]]
file = "config/bluemap/core.conf"
hash = "328d8db69db4bd1afb8403c1178918f0f080fdf69dfddeb5e0aea837f28e0983"

[[files]]
file = "config/bluemap/maps/world.conf"
hash = "9f9fe5853b843634499b3683ce35bcb537d2ff883d5fecc5459642cc282d35a3"

[[files]]
file = "config/bluemap/maps/world_the_end.conf"
hash = "5798827c56d1c1f0982e29204417e635d900f1e2a6d1af12352eca40e14ca40e"

[[files]]
file = "config/bluemap/maps/world_the_nether.conf"
hash = "e07f6cd2d2db904b3beebb30d8c2389c42ea2939211ce7f2caef87b1b5494673"

[[files]]
file = "config/bluemap/plugin.conf"
hash = "84121af20e755f22e18e04339e2a658e9c240b4c67c3abb24b50ba588925b039"

[[files]]
file = "config/bluemap/storages/file.conf"
hash = "ce1f7419cb657755fcb3266817251951701119b95c8e34fb8fa0a1f6be8c7b17"

[[files]]
file = "config/bluemap/storages/sql.conf"
hash = "dbf122b4932a67e8b602ebe24d3278616522c24d2e9481f6c31c9949e75ed9f6"

[[files]]
file = "config/bluemap/webapp.conf"
hash = "01f06e0eff76f950e4152dedd36687b599777cb24a1ce4699137b1025c6288dc"

[[files]]
file = "config/bluemap/webserver.conf"
hash = "420b13227864623ff9e5f200ebba4c1a10f05a4ca40539dbefdfc9e23cdf78f2"

[[files]]
file = "config/luckperms/luckperms.conf"
hash = "d3076fcb9ece3a3b93e172f6cf230494fccdd530d6d79b873b35f76b5125c253"

[[files]]
file = "luckperms/yaml-storage/groups/default.yml"
hash = "bc90b8909f6e52ed2b575b7b3891853735af74a44f3198f3665c0346b7d0fd3a"

[[files]]
file = "luckperms/yaml-storage/users/b4d855e0-e20c-4cb3-9a03-9af7e3eb1bda.yml"
hash = "4bd7c892ddae19d7fb87e4a34b577d8559191c0fe1c0b893fd2684538e897601"

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "ff1763afa21669a76a9ca65735944986ec4ef7a0d440b98ee2154aafa46356c8"
metafile = true

[[files]]
file = "mods/bluemap.pw.toml"
hash = "853ba2ec022456ae2f357268a27c7cb1018b0c57e0c1e9071330f81e035f59f9"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "ff260b35492778bdce59ffa064a59c6a9953ffd409eb40782af14b78a29a2cb8"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "479cc9008a66ce4dea0b0be0f749a986d73f5fe778516d6682a5202e19706179"
metafile = true

[[files]]
file = "mods/easyauth.pw.toml"
hash = "4bad5720d383f38e68af1a423c66808a966845a362216548eba010608fa4e2fd"
metafile = true

[[files]]
file = "mods/easywhitelist.pw.toml"
hash = "f7c8b837c3517826fa33490a20dbd290bf0f5917946f8dcae6584725b5f7a5da"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "39b4f43a271700276ff1ae632cf05f90b85f79670d955b50ced036e363a0efe9"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "61afd7af5c645ffd966b2bd86be944eacd1e48a8044e8f67082225d4d9989f0c"
metafile = true

[[files]]
file = "mods/fabricexporter.pw.toml"
hash = "507d6c5b9774a05a58e60b67692830d0637c4348b07b1d162224823e39dcb68f"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "76a12a836d4c7f0f943a1e391dd2d7b5c4673caa497fff16593d49449376b117"
metafile = true

[[files]]
file = "mods/floodgate.pw.toml"
hash = "ece34207ca75882863aa616328af686011fd554595b80a7858ddcc4848d5768d"
metafile = true

[[files]]
file = "mods/geyser.pw.toml"
hash = "726a9f5ed39577d00c1ef6e87ab81c91d985ef5961af89d7a9de793afd8a2a30"
metafile = true

[[files]]
file = "mods/grimac.pw.toml"
hash = "cc809ea025318e35b2300bfbd2bf6b60874898c2a7c40b1fcf3b0fe356e4e3c7"
metafile = true

[[files]]
file = "mods/ledger.pw.toml"
hash = "052f06542206356664307ad7f73ef7d37123da055dc362f13cfe76839afdb73a"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "0e87ab10adb3db84b1d6d2ce8bdd7158878b56c965055056b10ad6cde2634568"
metafile = true

[[files]]
file = "mods/luckperms.pw.toml"
hash = "0fcb21a2580ad82270c404aa36e042926a7f35b0151f785bd6c6afce23e6edc4"
metafile = true

[[files]]
file = "mods/mob-heads.pw.toml"
hash = "c3d78afbbcc00505d5005c23c3772e3fa07e088b6187eda9a5eed7d837bacc71"
metafile = true

[[files]]
file = "mods/notenoughcrashes.pw.toml"
hash = "772dfab5c9623199bf2438c5e8d836f0fc480c33d9f4517759074c69cdcbe89e"
metafile = true

[[files]]
file = "mods/player-drops-head.pw.toml"
hash = "a7df90e503c6b85156d3224f025807dcfb54032930376bb19218033fdd1f6c87"
metafile = true

[[files]]
file = "mods/scalablelux.pw.toml"
hash = "936e9028071f4e49ecd551aadab4c161f9a7143764b4cc89f8077296bd8645a6"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "9ff1a261860fcb16a7c7f124d738abcdfc1297363412d237540685003ff04d6b"
metafile = true

[[files]]
file = "mods/skinsrestorer.pw.toml"
hash = "4931535bd01a12d092e2e649d7a53e8404b02c944d93ff71c3b343e457817ce1"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "c073f13897a838e3c409e46b8a1d8cb510d6a6584dd815aeadaf4886f1779513"
metafile = true

[[files]]
file = "mods/statsmod.pw.toml"
hash = "54acb45b90bace0ccc5e99a583deaabf51d16327194a5d9ca45870effe0ad807"
metafile = true

[[files]]
file = "mods/tcdcommons.pw.toml"
hash = "cf2a50560f03613b7356103544a1f11d38da73fc445b5ec0b5a29c10543c3cfd"
metafile = true

[[files]]
file = "mods/vanish.pw.toml"
hash = "03e7ff71a73cf26ace9eda49606f2baa1d78dcac585d494478dd605e06f63ba8"
metafile = true

[[files]]
file = "mods/viabackwards.pw.toml"
hash = "43e7b9b99eed20ee395b09e3313844b006ea4ae12f52975405a1637a085725ec"
metafile = true

[[files]]
file = "mods/viafabric.pw.toml"
hash = "3afb8146397199564ddc80b33cba08e289f9bfd10720fb548262aee631fa97f8"
metafile = true

[[files]]
file = "mods/viaversion.pw.toml"
hash = "efc5c879cda829efd15fb8bc3bc1bfb218fc7502b5d0a85d495d8b33d58180e3"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
hash = "5aed63b141e338e9eace980e591b108312cb68d053b33eb54f2a2d749cc20514"
metafile = true
