name = "Queer Minecraft Server Modpack"
author = "arc2-group"
version = "3.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e38314963461af8e9f3058f3d2e7d59b7a892563ec02f564e923730264d1dbd1"

[versions]
fabric = "0.18.3"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.21.10"]
