name = "Queer Minecraft Server Modpack"
author = "arc2-group"
version = "3.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "96642b9177010ac1541fb494bd031dfc55b7bea424240c61645ab7ad0117d9a6"

[versions]
fabric = "0.18.3"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.21.10"]
