name = "Queer Minecraft Server Modpack"
author = "arc2-group"
version = "3.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e4425a1db54132cc9baf1e91a3fb80ce7215c532d7acb114266d6a354f2bb9c6"

[versions]
fabric = "0.18.3"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.21.10"]
