name = "Queer Minecraft Server Modpack"
author = "arc2-group"
version = "3.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2aeb8f011c28bb6c7fc559ebe95d0b712dbc84e5d17374a2ba162a167424e1bc"

[versions]
fabric = "0.18.3"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.21.10"]
